### ISSUE TITLE
Integration not working (HA 0.118)

### ISSUE THREAD

**Issue by Nattfisk** [IDmedia/hass-samsung_soundbar#2]
Tried to set this up through HACS using the following config:

> media_player:
>   - platform: samsung_soundbar
>     name: "Samsung Soundbar"
>     host: 192.168.1.178
>     port: 55001
>     max_volume: 30
>     power_options: True

But it does not seem to work. the device just shows as offline.

I have tried to send API commands manually, and that seems to work, so the port and IP is definately correct.

**Comment by IDmedia** [comment]
What soundbar do you have?
Have you tried opening your browser and navigating to http://192.168.1.178:55001/ ? Does it timeout or do you get any kind of message? I have a Q90R and have to use port 56001. If I open that link in my browser (http://192.168.1.80:56001/) it says "401 Unauthorized" telling me that it listens on that IP and port.

**Comment by Nattfisk** [comment]
> 
> 
> What soundbar do you have?
> Have you tried opening your browser and navigating to http://192.168.1.178:55001/ ? Does it timeout or do you get any kind of message? I have a Q90R and have to use port 56001. If I open that link in my browser (http://192.168.1.80:56001/) it says "401 Unauthorized" telling me that it listens on that IP and port.

Wow, did not anticipate such a quick reply :)
I Have a HW-K950, and when browsing the IP I get a "401 Unauthorized".

**Comment by IDmedia** [comment]
Strange, thought most of the Samsung soundbar had the same API.. I'll look into it later today and see if I can figure out something.

**Comment by IDmedia** [comment]
Could you try this link in your browser and see what the soundbar returns? [](http://192.168.1.178:55001/UIC?cmd=%3Cname%3EGetPowerStatus%3C/name%3E)
Does the log in Home Assistant give you any more information?

You shuld also be able to control (turn on/off) your soundbar from the bowser using this URL.
Change VAL to 1 for ON or 0 for OFF
[](http://192.168.1.178:55001/UIC?cmd=<name>SetPowerStatus</name><p type="dec" name="powerStatus" val="0"/>)

**Comment by Biliskn3r** [comment]
Same issue here. I have the K650. 

No other logs in HA: 2020-12-24 16:56:10 INFO (MainThread) [custom_components.samsung_soundbar.media_player] Refreshing state...

I can get the not authorised msg but sending commands (UIC?cmd=%3Cname%3EGetPowerStatus%3C/name%3E     and    UIC?cmd=<name>SetPowerStatus</name><p type="dec" name="powerStatus" val="0"/>) 

Just get a webpage time-out . Nothing helpful :( 

Tried curl as well and the prompt just sits there obviously no response... sometimes I get this straightaway:
------------------------------------
curl 'http://xxxxxxx:55001/UIC?cmd=%3Cname%3EGetPowerStatus%3C/name%3E'

StatusCode        : 200
StatusDescription : OK
Content           : <?xml version="1.0" encoding="UTF-8"?><UIC><method>RequestDeviceInfo</method><version>1.0</version><speakerip>xxxxxxx</speakerip><user_identifier>73a9ca7xxxxx579079893</user_identifie...
RawContent        : HTTP/1.1 200 OK
                    Connection: close
                    Content-Length: 241
                    Content-Type: text/html
                    Date: Sat, 03 Jan 1970 13:28:13 GMT
                    Last-Modified: Sat, 03 Jan 1970 13:28:13 GMT
                    Server: Samsung/1.0

                    <?xml versio...
Forms             : {}
Headers           : {[Connection, close], [Content-Length, 241], [Content-Type, text/html], [Date, Sat, 03 Jan 1970 13:28:13 GMT]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 241

**Comment by Biliskn3r** [comment]
Same issue here. I have the K650.

No other logs in HA: 2020-12-24 16:56:10 INFO (MainThread) [custom_components.samsung_soundbar.media_player] Refreshing state...

I can get the not authorised msg but sending commands (UIC?cmd=%3Cname%3EGetPowerStatus%3C/name%3E and UIC?cmd=SetPowerStatus

)

Just get a webpage time-out . Nothing helpful :(

Tried curl as well and the prompt just sits there obviously no response... sometimes I get this straightaway:
curl 'http://xxxxxxx:55001/UIC?cmd=%3Cname%3EGetPowerStatus%3C/name%3E'

StatusCode : 200
StatusDescription : OK
Content : RequestDeviceInfo1.0xxxxxxx<user_identifier>73a9ca7xxxxx579079893</user_identifie...
RawContent : HTTP/1.1 200 OK
Connection: close
Content-Length: 241
Content-Type: text/html
Date: Sat, 03 Jan 1970 13:28:13 GMT
Last-Modified: Sat, 03 Jan 1970 13:28:13 GMT
Server: Samsung/1.0

                <?xml versio...
Forms : {}
Headers : {[Connection, close], [Content-Length, 241], [Content-Type, text/html], [Date, Sat, 03 Jan 1970 13:28:13 GMT]...}
Images : {}
InputFields : {}
Links : {}
ParsedHtml : mshtml.HTMLDocumentClass
RawContentLength : 241

**Comment by odelay** [comment]
I have a HW-K950 in the past it was working fine with macbury's solution. Did any one have it working with a K950 or K650?
No errors are logged and no new media_player appears in HA. Tried it with both power option True and False. 

UIC?cmd=%3Cname%3EGetPowerStatus%3C/name%3E is not working 

IDmedia, could you help me to solve it?

**Comment by alghazu** [comment]
I have a HW-K950 , when i send the power command, the browser keeps waiting, when i click the volume, the browser gets a reply with the volume value.

VolumeLevel1.0192.168.0.35public11

**Comment by Allsimon** [comment]
I'm getting the exact same behaviour than @alghazu with a HW-J7500

**Comment by IDmedia** [comment]
I'll try to look into this later this week

**Comment by iFEARR** [comment]
Any updates on this ?

I have a HW-S61A and this just times out, can't even check configuration in ha.

I've tried `http://10.0.0.233:56001/UIC?cmd=%3Cname%3ESetPowerStatus%3C/name%3E%3Cp%20type=%22dec%22%20name=%22powerStatus%22%20val=%221%22/%3E` and it works. My port is 56001 tho, 55000 is also open.

Apparently on wrong url format/comand it times out for some reason.

**Comment by IDmedia** [comment]
Not yet. I have unfortunately barely any time to work on this due to covid and work. It's still on my doto-list as HA states this will stop working in 2022 I'll have fix it by the next major version. :) Still not sure how many variants there of this API, so I'll try to go through all messages here once I get more time and maybe make a small script that will help me determine the capabilities of each soundbar.

**Comment by inancatil** [comment]
> Could you try this link in your browser and see what the soundbar returns? `http://192.168.1.178:55001/UIC?cmd=%3Cname%3EGetPowerStatus%3C/name%3E`
> 
> You shuld also be able to control (turn on/off) your soundbar from the bowser using this URL. Change VAL to 1 for ON or 0 for OFF `http://192.168.1.178:55001/UIC?cmd=<name>SetPowerStatus</name><p type="dec" name="powerStatus" val="0"/>`
> 
> Does the log in Home Assistant give you any more information?

Hi, 
I am able to send on/off command with url but I couldn't figure out how to use my sound bar as media playback device. When I hit play on spotify I get "Failed to call service media_player/media_play. No active playback device found".
