### ISSUE TITLE
Error: Entity media_player.soundbar does not support this service

### ISSUE THREAD

**Issue by FancyNerd92** [IDmedia/hass-samsung_soundbar#7]
I'm getting the error "Entity media_player.soundbar does not support this service" when try to play an automation from TTS. When trying to group my Samsung Soundbar Q950A with other Google Nest speakers the TTS mp3 file playing only on Google Nest speakers. I want to add my soundbar to my All Home Speakers Group on HA to make multiroom audio for my living room, all other home have Google Nest Audio and Mini. After all missing the "Browse Media" on media player so the soundbar it's unusable on HA at all...

Why this error?

**Comment by IDmedia** [comment]
I don't know as I don't use it for TTS so it's not something I support unfortunately
